#!/bin/bash --login

# Get the directory of the script
SCRIPT_DIR=$(dirname "$0")
SCRIPT_PARENT_DIR=$(
    cd "$SCRIPT_DIR/.."
    pwd
)

if ! $SCRIPT_DIR/voichai-checkInstall; then
    echo "Some dependences have to be installed first." 1>&2
    exit 1
fi

if ! ps -ef | grep voichai-server.py | grep -v grep; then
    cd "$SCRIPT_DIR/../server/src"
    nohup python3.9 voichai-server.py >>/tmp/voichai-server.log 2>&1 &
    TOTAL=5
    count=0
    while ! curl http://127.0.0.1:4999/ >/dev/null 2>&1; do
        ((count++))
        if [ $count -ge $TOTAL ]; then
            echo "Failed: python3.9 voichai-server.py!" 1>&2
            exit 1
        fi
        sleep 1
    done
    cd - >/dev/null
fi

if ! ps -ef | grep ./voichai-client | grep -v grep; then
    cd "$SCRIPT_DIR"
    nohup ./voichai-client >>/tmp/voichai-client.log 2>&1 &
    cd - >/dev/null
    TOTAL=5
    count=0
    while ! curl http://localhost:3999/ >/dev/null 2>&1; do
        ((count++))
        if [ $count -ge $TOTAL ]; then
            echo "Failed: npm run dev!" 1>&2
            exit 1
        fi
        sleep 1
    done
    cat "/tmp/voichai-npm.log" | tail -n 7
fi

exit 0
